import { Component, ViewEncapsulation } from '@angular/core';
import { MbscCalendarEvent, MbscEventcalendarView, MbscResource, Notifications, setOptions /* localeImport */ } from '@mobiscroll/angular';
import { dyndatetime } from '../../../../app/app.util';

setOptions({
  // locale,
  // theme,
});

@Component({
  styleUrl: './content-dependent-resource-width.css',
  selector: 'app-scheduler-content-dependent-resource-widths',
  templateUrl: './content-dependent-resource-width.html',
  encapsulation: ViewEncapsulation.None,
  providers: [Notifications],
})
export class AppComponent {
  myEvents: MbscCalendarEvent[] = [
    {
      id: 1,
      resource: 1,
      title: 'Bug Fix',
      start: dyndatetime('y, m, d, 9, 15'),
      end: dyndatetime('y, m, d, 10, 45'),
    },
    {
      id: 2,
      resource: 3,
      title: 'API Integration',
      start: dyndatetime('y, m, d, 9, 0'),
      end: dyndatetime('y, m, d, 11, 0'),
    },
    {
      id: 3,
      resource: 4,
      title: 'Ticket Resolution',
      start: dyndatetime('y, m, d, 12, 30'),
      end: dyndatetime('y, m, d, 15, 0'),
    },
    {
      id: 4,
      resource: 3,
      title: 'Code Optimization',
      start: dyndatetime('y, m, d, 15, 30'),
      end: dyndatetime('y, m, d, 17, 15'),
    },
    {
      id: 5,
      resource: 1,
      title: 'Performance Tuning',
      start: dyndatetime('y, m, d, 14, 45'),
      end: dyndatetime('y, m, d, 16, 0'),
    },
    {
      id: 6,
      resource: 1,
      title: 'Deploy Patch',
      start: dyndatetime('y, m, d + 2, 9, 0'),
      end: dyndatetime('y, m, d + 2, 10, 30'),
    },
    {
      id: 7,
      resource: 4,
      title: 'Follow-up Support',
      start: dyndatetime('y, m, d + 2, 13, 0'),
      end: dyndatetime('y, m, d + 2, 15, 0'),
    },
    {
      id: 8,
      resource: 3,
      title: 'Incident Review',
      start: dyndatetime('y, m, d + 2, 16, 0'),
      end: dyndatetime('y, m, d + 2, 18, 0'),
    },
    {
      id: 9,
      resource: 3,
      title: 'API Debugging',
      start: dyndatetime('y, m, d + 2, 10, 15'),
      end: dyndatetime('y, m, d + 2, 12, 15'),
    },
    {
      id: 10,
      resource: 1,
      title: 'DB Cleanup',
      start: dyndatetime('y, m, d + 3, 15, 0'),
      end: dyndatetime('y, m, d + 3, 16, 30'),
    },
    {
      id: 11,
      resource: 3,
      title: 'Code Review',
      start: dyndatetime('y, m, d + 3, 9, 45'),
      end: dyndatetime('y, m, d + 3, 11, 15'),
    },
    {
      id: 12,
      resource: 3,
      title: 'System Update',
      start: dyndatetime('y, m, d + 3, 12, 45'),
      end: dyndatetime('y, m, d + 3, 15, 0'),
    },
    {
      id: 13,
      resource: 4,
      title: 'Escalation Handling',
      start: dyndatetime('y, m, d + 3, 15, 0'),
      end: dyndatetime('y, m, d + 3, 17, 30'),
    },
    {
      id: 14,
      resource: 1,
      title: 'Code Review',
      start: dyndatetime('y, m, d + 1, 11, 0'),
      end: dyndatetime('y, m, d + 1, 12, 30'),
    },
    {
      id: 15,
      resource: 3,
      title: 'Ticket Handling',
      start: dyndatetime('y, m, d + 1, 15, 45'),
      end: dyndatetime('y, m, d + 1, 17, 15'),
    },
    {
      id: 16,
      resource: 4,
      title: 'Live Chat',
      start: dyndatetime('y, m, d + 1, 11, 0'),
      end: dyndatetime('y, m, d + 1, 13, 0'),
    },
    {
      id: 17,
      resource: 3,
      title: 'Event Review',
      start: dyndatetime('y, m, d + 1, 8, 15'),
      end: dyndatetime('y, m, d + 1, 9, 45'),
    },
    {
      id: 18,
      resource: 3,
      title: 'Event Update',
      start: dyndatetime('y, m, d + 1, 12, 30'),
      end: dyndatetime('y, m, d + 1, 14, 30'),
    },
    {
      id: 19,
      resource: 1,
      title: 'Performance Test',
      start: dyndatetime('y, m, d + 4, 9, 30'),
      end: dyndatetime('y, m, d + 4, 11, 0'),
    },
    {
      id: 20,
      resource: 3,
      title: 'Query Optimization',
      start: dyndatetime('y, m, d + 4, 11, 30'),
      end: dyndatetime('y, m, d + 4, 13, 15'),
    },
    {
      id: 21,
      resource: 3,
      title: 'Patch Review',
      start: dyndatetime('y, m, d + 4, 15, 45'),
      end: dyndatetime('y, m, d + 4, 17, 30'),
    },
    {
      id: 22,
      resource: 4,
      title: 'Support Call',
      start: dyndatetime('y, m, d + 4, 9, 15'),
      end: dyndatetime('y, m, d + 4, 11, 30'),
    },
    {
      id: 23,
      resource: 4,
      title: 'Issue Resolution',
      start: dyndatetime('y, m, d + 4, 13, 0'),
      end: dyndatetime('y, m, d + 4, 15, 0'),
    },
    {
      id: 24,
      resource: 4,
      title: 'Support Review',
      start: dyndatetime('y, m, d - 1, 10, 15'),
      end: dyndatetime('y, m, d - 1, 12, 0'),
    },
    {
      id: 25,
      resource: 4,
      title: 'Ticket Update',
      start: dyndatetime('y, m, d - 1, 13, 0'),
      end: dyndatetime('y, m, d - 1, 15, 0'),
    },
    {
      id: 26,
      resource: 3,
      title: 'System Test',
      start: dyndatetime('y, m, d - 1, 9, 0'),
      end: dyndatetime('y, m, d - 1, 10, 30'),
    },
    {
      id: 27,
      resource: 3,
      title: 'API Testing',
      start: dyndatetime('y, m, d - 1, 13, 30'),
      end: dyndatetime('y, m, d - 1, 15, 0'),
    },
    {
      id: 28,
      resource: 1,
      title: 'Code Review',
      start: dyndatetime('y, m, d - 1, 10, 0'),
      end: dyndatetime('y, m, d - 1, 10, 45'),
    },
    {
      id: 29,
      resource: 1,
      title: 'System Update',
      start: dyndatetime('y, m, d - 1, 11, 0'),
      end: dyndatetime('y, m, d - 1, 12, 30'),
    },
    {
      id: 30,
      resource: 1,
      title: 'Performance Test',
      start: dyndatetime('y, m, d - 1, 14, 45'),
      end: dyndatetime('y, m, d - 1, 15, 45'),
    },
    {
      id: 31,
      resource: 4,
      title: 'Escalation',
      start: dyndatetime('y, m, d - 2, 12, 15'),
      end: dyndatetime('y, m, d - 2, 14, 0'),
    },
    {
      id: 32,
      resource: 4,
      title: 'Live Support',
      start: dyndatetime('y, m, d - 2, 8, 15'),
      end: dyndatetime('y, m, d - 2, 10, 0'),
    },
    {
      id: 33,
      resource: 3,
      title: 'API Debugging',
      start: dyndatetime('y, m, d - 2, 11, 0'),
      end: dyndatetime('y, m, d - 2, 12, 45'),
    },
    {
      id: 34,
      resource: 3,
      title: 'Performance Check',
      start: dyndatetime('y, m, d - 2, 14, 45'),
      end: dyndatetime('y, m, d - 2, 16, 30'),
    },
    {
      id: 35,
      resource: 1,
      title: 'Code Optimization',
      start: dyndatetime('y, m, d - 2, 9, 0'),
      end: dyndatetime('y, m, d - 2, 10, 30'),
    },
    {
      id: 36,
      resource: 1,
      title: 'System Review',
      start: dyndatetime('y, m, d - 2, 13, 15'),
      end: dyndatetime('y, m, d - 2, 14, 45'),
    },
    {
      id: 37,
      resource: 4,
      title: 'Support Session',
      start: dyndatetime('y, m, d - 3, 11, 15'),
      end: dyndatetime('y, m, d - 3, 13, 0'),
    },
    {
      id: 38,
      resource: 3,
      title: 'Bug Fixing',
      start: dyndatetime('y, m, d - 3, 9, 15'),
      end: dyndatetime('y, m, d - 3, 11, 0'),
    },
    {
      id: 39,
      resource: 3,
      title: 'API Review',
      start: dyndatetime('y, m, d - 3, 14, 15'),
      end: dyndatetime('y, m, d - 3, 16, 0'),
    },
    {
      id: 40,
      resource: 1,
      title: 'DB Update',
      start: dyndatetime('y, m, d - 3, 12, 0'),
      end: dyndatetime('y, m, d - 3, 13, 0'),
    },
    {
      id: 41,
      resource: 1,
      title: 'Session',
      start: dyndatetime('y, m, d - 3, 10, 0'),
      end: dyndatetime('y, m, d - 3, 11, 0'),
    },
    {
      id: 42,
      resource: 1,
      title: 'Review',
      start: dyndatetime('y, m, d - 3, 15, 0'),
      end: dyndatetime('y, m, d - 3, 16, 0'),
    },
    {
      id: 43,
      resource: 4,
      title: 'Team Meet',
      start: dyndatetime('y, m, d - 4, 12, 30'),
      end: dyndatetime('y, m, d - 4, 14, 30'),
    },
    {
      id: 44,
      resource: 4,
      title: 'Client Meet',
      start: dyndatetime('y, m, d - 4, 8, 45'),
      end: dyndatetime('y, m, d - 4, 10, 30'),
    },
    {
      id: 45,
      resource: 3,
      title: 'Update Review',
      start: dyndatetime('y, m, d - 4, 14, 30'),
      end: dyndatetime('y, m, d - 4, 16, 45'),
    },
    {
      id: 46,
      resource: 3,
      title: 'Test Session',
      start: dyndatetime('y, m, d - 4, 10, 45'),
      end: dyndatetime('y, m, d - 4, 12, 15'),
    },
    {
      id: 47,
      resource: 1,
      title: 'Code Sync',
      start: dyndatetime('y, m, d - 4, 9, 15'),
      end: dyndatetime('y, m, d - 4, 11, 0'),
    },
    {
      id: 48,
      resource: 1,
      title: 'Dev Update',
      start: dyndatetime('y, m, d - 4, 13, 30'),
      end: dyndatetime('y, m, d - 4, 14, 30'),
    },
    {
      id: 49,
      resource: 4,
      title: 'Client Call',
      start: dyndatetime('y, m, d - 5, 11, 0'),
      end: dyndatetime('y, m, d - 5, 13, 0'),
    },
    {
      id: 50,
      resource: 4,
      title: 'Sync Meeting',
      start: dyndatetime('y, m, d - 5, 15, 0'),
      end: dyndatetime('y, m, d - 5, 16, 45'),
    },
    {
      id: 51,
      resource: 1,
      title: 'Standup',
      start: dyndatetime('y, m, d - 5, 10, 0'),
      end: dyndatetime('y, m, d - 5, 11, 0'),
    },
    {
      id: 52,
      resource: 3,
      title: 'Test Review',
      start: dyndatetime('y, m, d - 5, 13, 45'),
      end: dyndatetime('y, m, d - 5, 15, 0'),
    },
    {
      id: 53,
      resource: 3,
      title: 'Bug Fix',
      start: dyndatetime('y, m, d - 5, 9, 0'),
      end: dyndatetime('y, m, d - 5, 10, 0'),
    },
    {
      id: 54,
      resource: 3,
      title: 'API Debug',
      start: dyndatetime('y, m, d - 5, 11, 0'),
      end: dyndatetime('y, m, d - 5, 13, 0'),
    },
    {
      id: 55,
      resource: 1,
      title: 'Sync Up',
      start: dyndatetime('y, m, d - 7, 10, 0'),
      end: dyndatetime('y, m, d - 7, 11, 0'),
    },
    {
      id: 56,
      resource: 1,
      title: 'Team Sync',
      start: dyndatetime('y, m, d - 7, 14, 0'),
      end: dyndatetime('y, m, d - 7, 15, 0'),
    },
    {
      id: 57,
      resource: 3,
      title: 'Dev Test',
      start: dyndatetime('y, m, d - 7, 9, 0'),
      end: dyndatetime('y, m, d - 7, 11, 0'),
    },
    {
      id: 58,
      resource: 3,
      title: 'Bug Review',
      start: dyndatetime('y, m, d - 7, 12, 0'),
      end: dyndatetime('y, m, d - 7, 13, 30'),
    },
    {
      id: 59,
      resource: 3,
      title: 'API Test',
      start: dyndatetime('y, m, d - 7, 14, 30'),
      end: dyndatetime('y, m, d - 7, 17, 0'),
    },
    {
      id: 60,
      resource: 4,
      title: 'Client Sync',
      start: dyndatetime('y, m, d - 7, 10, 0'),
      end: dyndatetime('y, m, d - 7, 12, 0'),
    },
    {
      id: 61,
      resource: 1,
      title: 'Team Sync',
      start: dyndatetime('y, m, d - 6, 14, 0'),
      end: dyndatetime('y, m, d - 6, 15, 0'),
    },
    {
      id: 62,
      resource: 3,
      title: 'Test Event',
      start: dyndatetime('y, m, d - 6, 9, 30'),
      end: dyndatetime('y, m, d - 6, 12, 0'),
    },
    {
      id: 63,
      resource: 4,
      title: 'Sync Check',
      start: dyndatetime('y, m, d - 6, 12, 30'),
      end: dyndatetime('y, m, d - 6, 15, 0'),
    },
    {
      id: 64,
      resource: 4,
      title: 'Team Meeting',
      start: dyndatetime('y, m, d + 7, 9, 0'),
      end: dyndatetime('y, m, d + 7, 11, 0'),
    },
    {
      id: 65,
      resource: 4,
      title: 'Planning',
      start: dyndatetime('y, m, d + 7, 12, 0'),
      end: dyndatetime('y, m, d + 7, 13, 45'),
    },
    {
      id: 66,
      resource: 4,
      title: 'Quick Check',
      start: dyndatetime('y, m, d + 7, 15, 0'),
      end: dyndatetime('y, m, d + 7, 16, 45'),
    },
    {
      id: 67,
      resource: 3,
      title: 'Code Review',
      start: dyndatetime('y, m, d + 7, 9, 45'),
      end: dyndatetime('y, m, d + 7, 11, 30'),
    },
    {
      id: 68,
      resource: 3,
      title: 'Test Run',
      start: dyndatetime('y, m, d + 7, 12, 45'),
      end: dyndatetime('y, m, d + 7, 14, 0'),
    },
    {
      id: 69,
      resource: 1,
      title: 'Code Sync',
      start: dyndatetime('y, m, d + 7, 11, 15'),
      end: dyndatetime('y, m, d + 7, 12, 15'),
    },
    {
      id: 70,
      resource: 1,
      title: 'Dev Check',
      start: dyndatetime('y, m, d + 7, 14, 30'),
      end: dyndatetime('y, m, d + 7, 15, 30'),
    },
    {
      id: 71,
      resource: 1,
      title: 'Team Sync',
      start: dyndatetime('y, m, d + 7, 8, 45'),
      end: dyndatetime('y, m, d + 7, 9, 45'),
    },
    {
      id: 72,
      resource: 4,
      title: 'Team Meet',
      start: dyndatetime('y, m, d + 6, 8, 30'),
      end: dyndatetime('y, m, d + 6, 10, 45'),
    },
    {
      id: 73,
      resource: 4,
      title: 'Strategy Session',
      start: dyndatetime('y, m, d + 6, 14, 45'),
      end: dyndatetime('y, m, d + 6, 16, 45'),
    },
    {
      id: 74,
      resource: 3,
      title: 'Test Review',
      start: dyndatetime('y, m, d + 6, 9, 0'),
      end: dyndatetime('y, m, d + 6, 10, 30'),
    },
    {
      id: 75,
      resource: 3,
      title: 'API Check',
      start: dyndatetime('y, m, d + 6, 11, 15'),
      end: dyndatetime('y, m, d + 6, 12, 30'),
    },
    {
      id: 76,
      resource: 3,
      title: 'Feature Test',
      start: dyndatetime('y, m, d + 6, 16, 0'),
      end: dyndatetime('y, m, d + 6, 17, 45'),
    },
    {
      id: 77,
      resource: 1,
      title: 'Project Sync',
      start: dyndatetime('y, m, d + 6, 9, 15'),
      end: dyndatetime('y, m, d + 6, 11, 0'),
    },
    {
      id: 78,
      resource: 1,
      title: 'Team Meeting',
      start: dyndatetime('y, m, d + 6, 12, 30'),
      end: dyndatetime('y, m, d + 6, 13, 30'),
    },
    {
      id: 79,
      resource: 1,
      title: 'Review Session',
      start: dyndatetime('y, m, d + 6, 14, 30'),
      end: dyndatetime('y, m, d + 6, 15, 30'),
    },
    {
      id: 80,
      resource: 4,
      title: 'Code Check',
      start: dyndatetime('y, m, d + 5, 10, 15'),
      end: dyndatetime('y, m, d + 5, 12, 15'),
    },
    {
      id: 81,
      resource: 4,
      title: 'Team Sync',
      start: dyndatetime('y, m, d + 5, 13, 30'),
      end: dyndatetime('y, m, d + 5, 15, 30'),
    },
    {
      id: 82,
      resource: 3,
      title: 'Bug Review',
      start: dyndatetime('y, m, d + 5, 9, 0'),
      end: dyndatetime('y, m, d + 5, 10, 15'),
    },
    {
      id: 83,
      resource: 3,
      title: 'Feature Review',
      start: dyndatetime('y, m, d + 5, 12, 30'),
      end: dyndatetime('y, m, d + 5, 13, 45'),
    },
    {
      id: 84,
      resource: 3,
      title: 'API Sync',
      start: dyndatetime('y, m, d + 5, 15, 15'),
      end: dyndatetime('y, m, d + 5, 17, 0'),
    },
    {
      id: 85,
      resource: 1,
      title: 'Daily Sync',
      start: dyndatetime('y, m, d + 5, 9, 15'),
      end: dyndatetime('y, m, d + 5, 10, 15'),
    },
    {
      id: 86,
      resource: 1,
      title: 'Client Sync',
      start: dyndatetime('y, m, d + 5, 12, 0'),
      end: dyndatetime('y, m, d + 5, 13, 15'),
    },
    {
      id: 87,
      resource: 1,
      title: 'Final Review',
      start: dyndatetime('y, m, d + 5, 14, 45'),
      end: dyndatetime('y, m, d + 5, 16, 0'),
    },
    {
      id: 88,
      resource: 4,
      title: 'Ticket Triage',
      start: dyndatetime('y, m, d - 8, 11, 0'),
      end: dyndatetime('y, m, d - 8, 13, 0'),
    },
    {
      id: 89,
      resource: 1,
      title: 'Code Review',
      start: dyndatetime('y, m, d - 8, 9, 0'),
      end: dyndatetime('y, m, d - 8, 10, 30'),
    },
    {
      id: 90,
      resource: 1,
      title: 'API Testing',
      start: dyndatetime('y, m, d - 8, 12, 0'),
      end: dyndatetime('y, m, d - 8, 15, 0'),
    },
    {
      id: 91,
      resource: 3,
      title: 'Fix UI Bugs',
      start: dyndatetime('y, m, d - 8, 14, 0'),
      end: dyndatetime('y, m, d - 8, 16, 0'),
    },
    {
      id: 92,
      resource: 3,
      title: 'DB Optimize',
      start: dyndatetime('y, m, d - 8, 9, 0'),
      end: dyndatetime('y, m, d - 8, 11, 0'),
    },
    {
      id: 93,
      resource: 4,
      title: 'Live Chat Support',
      start: dyndatetime('y, m, d - 8, 16, 0'),
      end: dyndatetime('y, m, d - 8, 18, 0'),
    },
  ];
  myResources: MbscResource[] = [
    {
      id: 1,
      name: 'Adam Johnson',
      color: '#328e39',
      role: 'developer',
      inOffice: true,
      vacation: false,
      available: false,
      cssClass: 'mds-var-col-large',
    },
    {
      id: 2,
      name: 'Hannah Williams',
      color: '#00aabb',
      role: 'designer',
      inOffice: false,
      vacation: true,
      available: true,
      cssClass: 'mds-var-col-medium',
    },
    {
      id: 3,
      name: 'Charlie Smith',
      color: '#28B372.',
      role: 'developer',
      inOffice: true,
      vacation: false,
      available: true,
      cssClass: 'mds-var-col-medium',
    },
    {
      id: 4,
      name: 'Ethan Roberts',
      color: '#ff5733',
      role: 'support',
      inOffice: false,
      vacation: false,
      available: true,
      cssClass: 'mds-var-col-small',
    },
  ];

  myView: MbscEventcalendarView = {
    schedule: { type: 'week', startDay: 1, endDay: 5, startTime: '08:00', endTime: '19:00', allDay: false },
  };
}
