name: Sync demos to public repos

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 24

      - run: npm install fs-extra

      - run: node copy.js
        env:
          PUBLIC_REPOS_TOKEN: ${{ secrets.PUBLIC_REPOS_TOKEN }}
